CREATE TABLE `news_story` (
	`story_id` int(10) NOT NULL auto_increment,
	`story_title` varchar(255) NOT NULL,
	`story_subtitle` varchar(255) NOT NULL,
	`story_topic` int(10) NOT NULL,
	`story_type` varchar(25) NOT NULL,
	`story_short` text NOT NULL,
	`story_text` text NOT NULL,
	`story_words` varchar(255) NOT NULL,
	`story_desc` varchar(255) NOT NULL,
	`story_alias` varchar(255) NOT NULL,
	`story_important` tinyint(1) NOT NULL,
	`story_default` tinyint(1) NOT NULL,
	`story_status` tinyint(1) NOT NULL,
	`story_slide` tinyint(1) NOT NULL,
	`story_marquee` tinyint(1) NOT NULL,
	`story_create` int (10) NOT NULL,
	`story_update` int (10) NOT NULL,
	`story_publish` int (10) NOT NULL,
	`story_expire` int (10) NOT NULL,
	`story_uid` int(10) NOT NULL,
	`story_author` varchar(255) NOT NULL,
	`story_source` varchar(255) NOT NULL,
	`story_hits` int(10) NOT NULL,
	`story_img` varchar(255) NOT NULL,
	`story_comments` int(10) unsigned NOT NULL,
	`story_file` tinyint(3) NOT NULL,
	`story_rating` double(6,4) NOT NULL,
   `story_votes` int(10) unsigned NOT NULL,
	`dohtml` tinyint(1) NOT NULL,
	`dobr` tinyint(1) NOT NULL,
	`doimage` tinyint(1) NOT NULL,
	`dosmiley` tinyint(1) NOT NULL,
	`doxcode` tinyint(1) NOT NULL,
	PRIMARY KEY (`story_id`),
	UNIQUE KEY `story_alias` (`story_alias`),
	KEY `story_topic` (`story_topic`),
	KEY `story_title` (`story_title`),
	KEY `story_create` (`story_create`),
	KEY `story_publish` (`story_publish`),
   KEY `story_expire` (`story_expire`),
   KEY `story_uid` (`story_uid`),
   KEY `story_type` (`story_type`),
   KEY `select` (`story_topic`, `story_status`, `story_publish`, `story_expire`),
	FULLTEXT KEY `search` (`story_title`,`story_short`,`story_text`,`story_subtitle`)
) ENGINE=MyISAM;


CREATE TABLE `news_topic` (
	`topic_id` int (10) unsigned NOT NULL  auto_increment,
	`topic_pid` int (5) unsigned NOT NULL ,
	`topic_title` varchar (255)   NOT NULL ,
	`topic_desc` text   NOT NULL ,
	`topic_img` varchar (255)   NOT NULL ,
	`topic_weight` int (5)   NOT NULL ,
	`topic_showtype` tinyint (4)   NOT NULL ,
	`topic_perpage` tinyint (4)   NOT NULL ,
	`topic_columns` tinyint (4)   NOT NULL ,
	`topic_submitter` int (10)   NOT NULL,
	`topic_date_created` int (10)   NOT NULL,
	`topic_date_update` int (10)   NOT NULL,
	`topic_asmenu` tinyint (1)   NOT NULL default '1',
	`topic_online` tinyint (1)   NOT NULL default '1',
	`topic_showtopic` tinyint (1)   NOT NULL default '1',
	`topic_showsub` tinyint (1)   NOT NULL default '1',
	`topic_showauthor` tinyint (1)   NOT NULL default '1',
	`topic_showdate` tinyint (1)   NOT NULL default '1',
	`topic_showpdf` tinyint (1)   NOT NULL default '1',
	`topic_showprint` tinyint (1)   NOT NULL default '1',
	`topic_showmail` tinyint (1)   NOT NULL default '1',
	`topic_shownav` tinyint (1)   NOT NULL default '1',
	`topic_showhits` tinyint (1)   NOT NULL default '1',
	`topic_showcoms` tinyint (1)   NOT NULL default '1',
	`topic_alias` varchar(255) NOT NULL,
	`topic_homepage` tinyint (4)   NOT NULL ,
	`topic_show` tinyint (1)   NOT NULL default '1',
	`topic_style` varchar(64)   NOT NULL,
	PRIMARY KEY (`topic_id`),
	UNIQUE KEY `topic_alias` (`topic_alias`),
   KEY `topic_pid` (`topic_pid`),
   KEY `topic_online` (`topic_online`),
   KEY `topic_homepage` (`topic_homepage`)
) ENGINE=MyISAM;

CREATE TABLE `news_file` (
	`file_id` int (10) unsigned NOT NULL  auto_increment,
	`file_title` varchar (255)   NOT NULL ,
	`file_name` varchar (255)   NOT NULL ,
	`file_story` int(10) NOT NULL,
	`file_date` int(10) NOT NULL,
	`file_type` varchar(64) NOT NULL default '',
	`file_mimetype` varchar(64) NOT NULL default '',
	`file_status` tinyint(1) NOT NULL,
	`file_hits` int(10) NOT NULL,
	PRIMARY KEY (`file_id`),
	KEY `file_story` (`file_story`),
	KEY `file_status` (`file_status`),
	KEY `file_date` (`file_date`)
) ENGINE=MyISAM;

CREATE TABLE `news_rate` (
	`rate_id` int(10) unsigned NOT NULL auto_increment,
	`rate_story` int(8) unsigned NOT NULL,
	`rate_user` int(10) NOT NULL,
	`rate_rating` tinyint(3) unsigned NOT NULL,
	`rate_hostname` varchar(60) NOT NULL default '',
	`rate_created` int(10) NOT NULL,
	PRIMARY KEY  (`rate_id`),
	KEY `rate_user` (`rate_user`),
	KEY `rate_hostname` (`rate_hostname`),
	KEY `rate_story` (`rate_story`)
) ENGINE=MyISAM;